import { describe, expect, test } from "vite-plus/test";

import { testCommandResolutionsIn } from "./test-command-resolution.ts";

describe("testCommandResolutionsIn", () => {
  test.each([
    ["", []],
    ["echo ready && vp test", [{ kind: "not-test" }, { kind: "test", arguments: [] }]],
    ["env", [{ kind: "unresolved" }]],
    ["env -S", [{ kind: "unresolved" }]],
    ['env -S ""', [{ kind: "unresolved" }]],
    ['env -S "vp test"', [{ kind: "test", arguments: [] }]],
    ['env -S "vp test && echo hidden"', [{ kind: "unresolved" }]],
    ["env -Svp test --changed HEAD", [{ kind: "test", arguments: ["--changed", "HEAD"] }]],
    ["env TEST_CHILD=1 vp test", [{ kind: "test", arguments: [] }]],
    ["env -- vp test", [{ kind: "test", arguments: [] }]],
    ["env -Z vp test", [{ kind: "unresolved" }]],
    ["env -C", [{ kind: "unresolved" }]],
    ["env -C. vp test", [{ kind: "test", arguments: [] }]],
    ["command -p vp test", [{ kind: "test", arguments: [] }]],
    ["command -- vp test", [{ kind: "test", arguments: [] }]],
    ["command -x vp test", [{ kind: "unresolved" }]],
    ["command -v vp", [{ kind: "unresolved" }]],
    ["command", [{ kind: "unresolved" }]],
    ["exec", [{ kind: "unresolved" }]],
    ["exec --", [{ kind: "unresolved" }]],
    ["exec -- vp test", [{ kind: "test", arguments: [] }]],
    ["exec -a", [{ kind: "unresolved" }]],
    ["exec -a alias vp test", [{ kind: "test", arguments: [] }]],
    ["exec -c vp test", [{ kind: "test", arguments: [] }]],
    ["exec -Z vp test", [{ kind: "unresolved" }]],
    ["spool --", [{ kind: "unresolved" }]],
    ["spool vp test", [{ kind: "unresolved" }]],
    ["env env env env env env env env vp test", [{ kind: "unresolved" }]],
    ["npx --package", [{ kind: "unresolved" }]],
    ["npx --call fixture", [{ kind: "unresolved" }]],
    ["npx --call=fixture", [{ kind: "unresolved" }]],
    ["npx --unknown vitest", [{ kind: "unresolved" }]],
    ["npx --package=vitest vitest", [{ kind: "test", arguments: [] }]],
    ["npx --package vitest vitest", [{ kind: "test", arguments: [] }]],
    ["npx --yes vitest", [{ kind: "test", arguments: [] }]],
    ["npx --yes=true vitest", [{ kind: "test", arguments: [] }]],
    ["npm exec", [{ kind: "unresolved" }]],
    ["npm exec --", [{ kind: "unresolved" }]],
    ["npm exec --call fixture", [{ kind: "unresolved" }]],
    ["npm exec vitest", [{ kind: "test", arguments: [] }]],
    ["npm exec -- vitest", [{ kind: "test", arguments: [] }]],
    ["npm x -- vitest", [{ kind: "test", arguments: [] }]],
    ["pnpm exec vitest", [{ kind: "test", arguments: [] }]],
    ["vp exec -- vitest", [{ kind: "test", arguments: [] }]],
    ["vp run --unknown test", [{ kind: "unresolved" }]],
    ["vp run", [{ kind: "unresolved" }]],
    ["vp run test --changed HEAD", [{ kind: "test", arguments: ["--changed", "HEAD"] }]],
    ["vp run build", [{ kind: "not-test" }]],
    ["vp build", [{ kind: "not-test" }]],
    ["printf vp test", [{ kind: "not-test" }]],
    ["true", [{ kind: "not-test" }]],
    ["vitest@4 --changed HEAD", [{ kind: "test", arguments: ["--changed", "HEAD"] }]],
    ["./node_modules/.bin/vitest --coverage", [{ kind: "test", arguments: ["--coverage"] }]],
    ["unknown vp test", [{ kind: "unresolved" }]],
    ["CI=1", [{ kind: "unresolved" }]],
  ] as const)("resolves %s", (command, expected) => {
    expect(testCommandResolutionsIn(command)).toStrictEqual(expected);
  });
});
