import { describe, expect, test } from "vite-plus/test";

import { testCommandResolutionsIn } from "./test-command-resolution.ts";

const COMMAND_RESOLUTION_SCENARIOS = [
  ["", []],
  ["echo ready && vp test", [{ kind: "unresolved-test" }, { kind: "test", arguments: [] }]],
  ["vp test &", [{ kind: "unresolved-test" }]],
  ["true || vp test", [{ kind: "unresolved-test" }, { kind: "test", arguments: [] }]],
  ["env", [{ kind: "unresolved" }]],
  ["env -S", [{ kind: "unresolved-test" }]],
  ['env -S ""', [{ kind: "unresolved-test" }]],
  ['env -S "vp test"', [{ kind: "unresolved-test" }]],
  ['env -S "vp test && echo hidden"', [{ kind: "unresolved-test" }]],
  ['env -S "CI=1 vp test --config arbitrary.ts"', [{ kind: "unresolved-test" }]],
  ['env -S "env vp test --changed HEAD"', [{ kind: "unresolved-test" }]],
  ['env -S "vp exec -- vitest --coverage=false"', [{ kind: "unresolved-test" }]],
  ['env -S "vp test ${OPTION} arbitrary.ts"', [{ kind: "unresolved-test" }]],
  [String.raw`env -S 'vp\_test --config arbitrary.ts'`, [{ kind: "unresolved-test" }]],
  ["env -S '-i /tmp/fake/vp test --config arbitrary.ts'", [{ kind: "unresolved-test" }]],
  ["env -Svp test --changed HEAD", [{ kind: "unresolved-test" }]],
  ["env TEST_CHILD=1 vp test", [{ kind: "unresolved-test" }]],
  ["env -- vp test", [{ kind: "test", arguments: [] }]],
  ["env -Z vp test", [{ kind: "unresolved-test" }]],
  ["env -C", [{ kind: "unresolved-test" }]],
  ["env -C. vp test", [{ kind: "unresolved-test" }]],
  ["command -p vp test", [{ kind: "unresolved-test" }]],
  ["command -- vp test", [{ kind: "test", arguments: [] }]],
  ["command vp test", [{ kind: "test", arguments: [] }]],
  ["command -x vp test", [{ kind: "unresolved-test" }]],
  ["command -v vp", [{ kind: "unresolved-test" }]],
  ["command", [{ kind: "unresolved" }]],
  ["exec", [{ kind: "unresolved" }]],
  ["exec --", [{ kind: "unresolved" }]],
  ["exec -- vp test", [{ kind: "test", arguments: [] }]],
  ["exec -a", [{ kind: "unresolved-test" }]],
  ["exec -a alias vp test", [{ kind: "unresolved-test" }]],
  ["exec -c vp test", [{ kind: "unresolved-test" }]],
  ["exec -Z vp test", [{ kind: "unresolved-test" }]],
  ["spool --", [{ kind: "unresolved" }]],
  ["spool vp test", [{ kind: "unresolved" }]],
  ["env env env env env env env env vp test", [{ kind: "unresolved" }]],
  ["npx --package", [{ kind: "unresolved" }]],
  ["npx --call fixture", [{ kind: "unresolved" }]],
  ["npx --call=fixture", [{ kind: "unresolved" }]],
  ["npx --unknown vitest", [{ kind: "unresolved" }]],
  ["npx --package=vitest vitest", [{ kind: "unresolved" }]],
  ["npx --package vitest vitest", [{ kind: "unresolved" }]],
  ["npx --yes vitest", [{ kind: "unresolved" }]],
  ["npx --yes=true vitest", [{ kind: "unresolved" }]],
  ["npm exec", [{ kind: "unresolved" }]],
  ["npm exec --", [{ kind: "unresolved" }]],
  ["npm exec --call fixture", [{ kind: "unresolved" }]],
  ["npm exec vitest", [{ kind: "unresolved" }]],
  ["npm exec -- vitest", [{ kind: "unresolved" }]],
  ["npm x -- vitest", [{ kind: "unresolved" }]],
  ["pnpm exec vitest", [{ kind: "unresolved" }]],
  ["vp exec -- vitest", [{ kind: "not-test" }]],
  ["vp run --unknown test", [{ kind: "unresolved-test" }]],
  ["vp run", [{ kind: "unresolved-test" }]],
  ["vp run test --changed HEAD", [{ kind: "unresolved-test" }]],
  ["vp run build", [{ kind: "unresolved-test" }]],
  ["vp build", [{ kind: "not-test" }]],
  ["vp test run --coverage", [{ kind: "test", arguments: ["--coverage"] }]],
  ["vp test watch", [{ kind: "test", arguments: ["watch"] }]],
  ["vp test list", [{ kind: "test", arguments: ["list"] }]],
  ["vp test --help", [{ kind: "test", arguments: ["--help"] }]],
  ["vp test --clearCache", [{ kind: "test", arguments: ["--clearCache"] }]],
  ["vp test --root ../other", [{ kind: "test", arguments: ["--root", "../other"] }]],
  ["vp test -r../other", [{ kind: "test", arguments: ["-r../other"] }]],
  ["vitest --project other", [{ kind: "unresolved-test" }]],
  ["printf vp test", [{ kind: "not-test" }]],
  ["true", [{ kind: "not-test" }]],
  ["vitest@4 --changed HEAD", [{ kind: "unresolved" }]],
  ["vitest", [{ kind: "unresolved-test" }]],
  ["vitest run --coverage", [{ kind: "test", arguments: ["--coverage"] }]],
  ["vitest run run", [{ kind: "test", arguments: ["run"] }]],
  ["./node_modules/.bin/vitest", [{ kind: "unresolved-test" }]],
  ["./node_modules/.bin/vitest run --coverage", [{ kind: "test", arguments: ["--coverage"] }]],
  ["./node_modules/.bin/vitest run run", [{ kind: "test", arguments: ["run"] }]],
  ["./tools/vp test", [{ kind: "unresolved" }]],
  ["./tools/env vp test", [{ kind: "unresolved" }]],
  ["./tools/vitest", [{ kind: "unresolved" }]],
  ["vp\u00a0test", [{ kind: "unresolved" }]],
  ["vp\rtest", [{ kind: "unresolved" }]],
  ["unknown vp test", [{ kind: "unresolved" }]],
  ["unknown ${OPTION}", [{ kind: "unresolved" }]],
  ['echo "$OPTION"', [{ kind: "not-test" }]],
  ["CI=1", [{ kind: "unresolved-test" }]],
  ['"CI=1" vp test', [{ kind: "unresolved-test" }]],
  [String.raw`CI\=1 vp test`, [{ kind: "unresolved-test" }]],
  ['C"I"=1 vp test', [{ kind: "unresolved-test" }]],
  [
    "vp test --con${ANY:+}fig arbitrary.ts",
    [{ kind: "unresolved-test", arguments: ["--con${ANY:+}fig", "arbitrary.ts"] }],
  ],
  [
    'vp test "$(printf --config)" arbitrary.ts',
    [{ kind: "unresolved-test", arguments: ["$(printf --config)", "arbitrary.ts"] }],
  ],
  [
    "vp test `printf --config` arbitrary.ts",
    [{ kind: "unresolved-test", arguments: ["`printf", "--config`", "arbitrary.ts"] }],
  ],
  ["vp test '$OPTION'", [{ kind: "test", arguments: ["$OPTION"] }]],
  [String.raw`vp test \$OPTION`, [{ kind: "test", arguments: ["$OPTION"] }]],
  [
    String.raw`vp test \${OPTION:---config}`,
    [{ kind: "test", arguments: ["${OPTION:---config}"] }],
  ],
  ['vp test prefix"-suffix"', [{ kind: "test", arguments: ["prefix-suffix"] }]],
  ["vp test \"'$OPTION'\"", [{ kind: "unresolved-test", arguments: ["'$OPTION'"] }]],
  [
    String.raw`vp test --con\
fig arbitrary.ts`,
    [{ kind: "test", arguments: ["--config", "arbitrary.ts"] }],
  ],
  ["vp test --con{fig,other}", [{ kind: "unresolved-test", arguments: ["--con{fig,other}"] }]],
  ["vp test --confi?", [{ kind: "unresolved-test", arguments: ["--confi?"] }]],
  [String.raw`vp test '--con\fig'`, [{ kind: "test", arguments: [String.raw`--con\fig`] }]],
  [String.raw`vp test --con\"fig`, [{ kind: "test", arguments: ['--con"fig'] }]],
  [String.raw`vp test "foo\q"`, [{ kind: "test", arguments: [String.raw`foo\q`] }]],
  [String.raw`vp test "foo\$bar"`, [{ kind: "test", arguments: ["foo$bar"] }]],
  [
    String.raw`vp \
 test`,
    [{ kind: "test", arguments: [] }],
  ],
  ["vp test \"'--config'\"", [{ kind: "test", arguments: ["'--config'"] }]],
  ["vp test # --config arbitrary.ts", [{ kind: "test", arguments: [] }]],
  ["vp test # ' --config arbitrary.ts", [{ kind: "test", arguments: [] }]],
  [
    String.raw`vp test # comment \
vp test --config arbitrary.ts`,
    [{ kind: "unresolved-test" }, { kind: "test", arguments: ["--config", "arbitrary.ts"] }],
  ],
  [
    String.raw`vp test \
# --config arbitrary.ts`,
    [{ kind: "test", arguments: [] }],
  ],
  [
    String.raw`vp test foo\
# --config arbitrary.ts`,
    [{ kind: "test", arguments: ["foo#", "--config", "arbitrary.ts"] }],
  ],
  [
    "vp test # --config\nvp test --changed HEAD",
    [{ kind: "unresolved-test" }, { kind: "test", arguments: ["--changed", "HEAD"] }],
  ],
  ["vp test foo#bar", [{ kind: "test", arguments: ["foo#bar"] }]],
  ["vp test '# --config'", [{ kind: "test", arguments: ["# --config"] }]],
  ["vp test > --config", [{ kind: "test", arguments: [] }]],
  ['vp test > "$LOG"', [{ kind: "test", arguments: [] }]],
  [
    'vp test > "$(vp test --config arbitrary.ts; printf outer.log)"',
    [{ kind: "unresolved-test", arguments: [] }],
  ],
  ["vp test > `printf outer.log`", [{ kind: "unresolved-test", arguments: ["outer.log`"] }]],
  ["vp test > >(printf outer.log)", [{ kind: "unresolved-test", arguments: ["outer.log)"] }]],
  ["vp test >(printf outer.log)", [{ kind: "unresolved-test", arguments: ["outer.log)"] }]],
  ["vp test 2> --coverage.exclude=x", [{ kind: "test", arguments: [] }]],
  ["vp test < --changed", [{ kind: "test", arguments: [] }]],
  ["vp test 'unterminated", [{ kind: "unresolved-test", arguments: ["unterminated"] }]],
] as const;

describe("testCommandResolutionsIn", () => {
  describe.each(COMMAND_RESOLUTION_SCENARIOS)("%s", (commandSource, expectedResolutions) => {
    const it = test.extend("commandResolutions", () => testCommandResolutionsIn(commandSource));

    it("resolves the command", ({ commandResolutions }) => {
      expect(commandResolutions).toStrictEqual(expectedResolutions);
    });
  });
});
